apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
#livenessProbe.httpGet: HTTP GET을 수행하는 라이브니스 프로브
#livenessProbe.httpGet.{path&port}: HTTP 요청 경로 및 포트
#컨테이너 실행 즉시 프로브 시작
#kubectl describe po kubia-liveness 로 프로세스 비정상 종료 및 라이브니스 정보 확인
