apiVersion: v1
kind: Pod #오브젝트 종류
metadata:
  name: kubia-manual #파드명
spec:
  containers:
  - image: luksa/kubia #컨테이너를 만들 때 사용할 이미지
    name: kubia # 컨테이너명
    ports: #애플리케이션이 수신하는 포트/단순히 정보 기록용(기본적으로 모든 포트 개방하기 때문)
    - containerPort: 8080
      protocol: TCP
