apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-network
spec:
  hostNetwork: true
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
#hostNetwork: true 속성을 사용해 호스트의 네트워크 네임스페이스를 사용한다.