apiVersion: v1
kind: Pod
metadata:
  name: pod-add-settime-capability
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      capabilities:
        add:
        - SYS_TIME

#파드에 SYS_TIME 커널 접근 권한을 추가해 시간 변경 가능
#kubectl exec -it pod-add-settime-capability -- date +%T -s "12:00:00"
#세부 기능을 추가하는 것이 특권보다 훨씬 안전한 방법